### ISSUE TITLE
ghci fails with "unable to load package `integer-gmp-1.0.0.1'"

### ISSUE THREAD

**Issue by KaiHa** [snowleopard/hadrian#259]
After building ghc with hadrian the invocation of `../inplace/bin/ghc-stage2 --interactive` fails with the following error message:

```
../inplace/bin/ghc-stage2 --interactiveGHCi, version 8.1.20160528: http://www.haskell.org/ghc/  :? for help
ghc-stage2: /home/kai/sw/FOSS/ghc/_build/stage1/libraries/integer-gmp/HSinteger-gmp-1.0.0.1.o: unhandled ELF relocation(RelA) type 42

ghc-stage2: unable to load package `integer-gmp-1.0.0.1'
```

Comparing the `ldd` output of the hadrian-build and the make-build unveils that the hadrian-build is missing a dependency:

```
libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10
```

I don't know if this is expected or if this is an consequence of the dynamic build issue referenced in an other ticket.

**Comment by snowleopard** [comment]
Thanks for reporting! I can't reproduce on my machine yet but I'm behind GHC HEAD. Will try to reproduce on HEAD soon.

**Comment by KaiHa** [comment]
For testing purposes I linked ghc against `libgmp` by altering the file `src/Settings/Builders/Ghc.hs`
```diff
@@ -45,4 +45,4 @@ ghcLinkArgs = builder (Ghc Link) ? do
     libDirs <- getPkgDataList DepLibDirs
     mconcat [ arg "-no-auto-link-packages"
-            , append [ "-optl-l" ++           lib | lib <- libs ++ gmpLibs ]
+            , append [ "-optl-l" ++           lib | lib <- libs ++ gmpLibs ++ ["gmp"] ]
             , append [ "-optl-L" ++ unifyPath dir | dir <- libDirs ] ]
```

but the above failure still persists.

I am building ghc 1e6701011425edb3553abc17c094a2a9faee4fd5
with hadrian 45b5f1341e3b400efeaa675ddc9d43d69268ff09
on a Debian (sid) amd64.

**Comment by michalt** [comment]
I can reproduce with today's GHC HEAD and Hadrian. I've run: 
`./hadrian/build.stack.sh --flavour=quick -j9 clean` followed by
`./hadrian/build.stack.sh --flavour=quick -j9`.

Interestingly I get more missing symbols (not only `integer-gmp`). Full output of running `inplace/bin/ghc-stage2 --interactive` below:
```
GHCi, version 8.1.20160531: http://www.haskell.org/ghc/  :? for help
ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a: unhandled ELF relocation(RelA) type 42

ghc-stage2: Could not on-demand load symbol '__gmpn_gcd_1'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a: unknown symbol `__gmpn_gcd_1'
ghc-stage2: Could not on-demand load symbol 'integer_gmp_powm_word'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a: unknown symbol `integer_gmp_powm_word'
ghc-stage2: Could not on-demand load symbol 'integerzmgmp_GHCziIntegerziType_integerToInt_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `integerzmgmp_GHCziIntegerziType_integerToInt_closure'
ghc-stage2: Could not on-demand load symbol 'base_GHCziInt_zdfReadInt8_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `base_GHCziInt_zdfReadInt8_closure'
ghc-stage2: Could not on-demand load symbol 'base_ForeignziCziTypes_zdfEqCInt_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `base_ForeignziCziTypes_zdfEqCInt_closure'
ghc-stage2: Could not on-demand load symbol 'base_GHCziIOziException_userError_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `base_GHCziIOziException_userError_closure'
ghc-stage2: Could not on-demand load symbol 'base_GHCziIO_failIO_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `base_GHCziIO_failIO_closure'
ghc-stage2: Could not on-demand load symbol 'base_GHCziBase_zpzp_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `base_GHCziBase_zpzp_closure'
ghc-stage2: Could not on-demand load symbol 'base_GHCziShow_showString_closure'

ghc-stage2: /home/michal/code/ghc0/_build/stage1/libraries/base/libHSbase-4.9.0.0.a: unknown symbol `base_GHCziShow_showString_closure'
ghc-stage2: Could not on-demand load symbol 'base_GHCziIOziHandleziTypes_NoBuffering_closure'

ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  base_GHCziIOziHandleziTypes_NoBuffering_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
```

**Comment by snowleopard** [comment]
I'm currently travelling and on a terrible Internet connection -- can't even checkout GHC HEAD. Will look into this as soon as I can.

The only possibly relevant recent change was done here: #241. If it is unrelated, then I'd suggest to do `git bisect` in GHC HEAD to identify the offending commit and see how Make build system copes with it.

**Comment by ndmitchell** [comment]
Simon Marlow always said that starting ghci and evaluating `1+2` is a relatively good smoke test that you got everything working. Perhaps add `ghc -e 1+2` to the Travis bots?

**Comment by snowleopard** [comment]
@ndmitchell Good idea, I didn't know we have `-e`! I've added this to Travis.

**Comment by snowleopard** [comment]
Oh, looks like there are other new breakages in GHC HEAD, in particular related to `@HaveLibdw@` flag. I'll try to fix this.

**Comment by snowleopard** [comment]
I've managed to build GHC HEAD on my Windows machine, but I can't reproduce this failure. Both `-e 1+2` and `--interactive` work fine for me.

**Comment by snowleopard** [comment]
The issue is now reproducible on the Travis Linux instance.

**Comment by snowleopard** [comment]
I think this issue is related to missing transitive dependencies. I must have introduced the bug when working on fixing #241.

**Comment by snowleopard** [comment]
I tried hard to catch a missing dependency, but so far everything appears to work correctly.

@KaiHa @michalt Is the bug deterministic on your machines? What happens if you rebuild the GHC executable only?

**Comment by snowleopard** [comment]
As @ndmitchell suggested, the issue could also be related to the *order* of files in some linker invocations.

**Comment by KaiHa** [comment]
> What happens if you rebuild the GHC executable only?

I rebuild by executing `rm inplace/lib/bin/ghc-stage2 inplace/bin/ghc-stage2; ./hadrian/build`. Is this the correct way to rebuild the GHC executable only?


> Is the bug deterministic on your machines?

If I rebuild in the above described way, the error still persists.

**Comment by snowleopard** [comment]
@KaiHa Yes, that's what I had in mind. Another experiment could be to also delete `integer-gmp` libraries `.a` and `.o` in `_build`, and rebuild GHC.

**Comment by KaiHa** [comment]
A `find _build -name "*integer-gmp*"` produces only the following results:
```
_build/stage1/libraries/integer-gmp
_build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1_p.a
_build/stage1/libraries/integer-gmp/libHSinteger-gmp-1.0.0.1.a
```
Is this what is expected?

**Comment by snowleopard** [comment]
This is strange: I believe there should also be something like `HSinteger-gmp-1.0.0.1.o`, which is a GHCi library. Will check this later, when I get to my machine.

**Comment by snowleopard** [comment]
Right, I confirm that the file `HSinteger-gmp-1.0.0.1.o` is also absenst on my machine. I'm not sure what's going on: 1) Why is it now absent? Most probably GHC has changed; 2) why doesn't this lead to link failures on Windows?

**Comment by snowleopard** [comment]
Ah, I've found the reason! :tada: 

@KaiHa In your commit https://github.com/snowleopard/hadrian/commit/123bdb37674bfe60509886ec92c99e80b0588966 you actually (rather stealthily!) changed the `dynamicGhcPrograms` from `False` to `True`, which disabled building static GHCi libraries, such as `HSinteger-gmp-1.0.0.1.o`. Because the whole file with user settings was replaced with a new one, I didn't spot this subtle change.

I have now reverted the change (since we don't currently support the `dynamic` way #4), and hopefully this will fix the issue.

P.S.: I still have no idea why Windows and Mac OS X do not care that these static GHCi libraries are missing. If anyone can clarify this, please do!

**Comment by KaiHa** [comment]
> @KaiHa In your commit 123bdb3 you actually (rather stealthily!) changed the dynamicGhcPrograms from False to True

Please accept my apologies for this stupid mistake of mine, I should have inspected my changes more thoroughly before I committed them.

> I have now reverted the change (since we don't currently support the dynamic way #4), and hopefully this will fix the issue.

I did a clean recompile with your change and most error messages disappear, but the initial one (`unhandled ELF relocation(RelA) type 42`) is still there. 

I removed the GHC executable and the directory `_build/stage1/libraries/integer-gmp` like you suggested and did a rebuild. But still the same error message appears. 

Travis also reports an error on Linux, albeit a different one (see https://s3.amazonaws.com/archive.travis-ci.org/jobs/136021796/log.txt).

@michalt do you still get the error (`unhandled ELF relocation(RelA) type 42`) when you recompile with Hadrian HEAD. And what does `as --version` report on your build system (I have 'as' in version 2.26)?

**Comment by snowleopard** [comment]
@KaiHa Don't worry about the accidental commit.

Yes, we still have a failure on Travis, but the number of errors is decreased too. Judging by the error, perhaps, now we are only missing a dependency on `base`? I just did a quick check on my machine (deleting `base`) but the dependency seems to be there.

**Comment by KaiHa** [comment]
In commit [56ceb5b5](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blobdiff;f=include/elf/x86-64.h;h=7b98f6542b5330167a4d420cf5dcfa57acea2732;hp=f18ec662db3afc155e8e13ed2f412de5dab9a5d0;hb=56ceb5b5405af23eddd12e12d8ba849010120324;hpb=02a866936de7e63ad4962ccba56c8cd05c231275) of the GNU Binutils the constant `R_X86_64_REX_GOTPCRELX` (42) was added. The corresponding case in GHCs [rts/Linker.c](http://git.haskell.org/ghc.git/blob/0d963caf40da4391028a3beb95b5082c87985e7d:/rts/Linker.c#l5687) is enabled by the compile time flags  `R_X86_64_REX_GOTPCRELX` and `R_X86_64_GOTPCRELX`.

**Comment by KaiHa** [comment]
OK, I think I know what the problem is. On my system the binutils have the version 2.26 but libc6 is still stuck at version 2.22. This means that the above mentioned constants (R_X86_64_REX_GOTPCRELX and R_X86_64_GOTPCRELX) are not defined in `/usr/include/elf.h`.

**Comment by KaiHa** [comment]
The remaining question is, why does the problem not arise when GHC is compiled the old way with the Makefile?

**Comment by thomie** [comment]
@KaiHa the old build system sets `DYNAMIC_GHC_PROGRAMS=YES` by default (on Linux), which means GHCi uses the system linker instead of the (buggy) RTS linker.

More info here: https://ghc.haskell.org/trac/ghc/wiki/DynamicGhcPrograms.

**Comment by KaiHa** [comment]
@thomie I have put 
```Makefile
DYNAMIC_GHC_PROGRAMS = NO
DYNAMIC_TOO = NO
```
into `mk/build.mk` in the hope that prevents the old build system from using the system linker.

**Comment by thomie** [comment]
Oh, then the old and the new build system should be doing the same thing.

**Comment by KaiHa** [comment]
@thomie I did a `ldd inplace/lib/bin/ghc-stage2` and it does not show me any `libHS` dependencies.

**Comment by thomie** [comment]
Oh, I can reproduce the `unknown symbol` issue with the old build system, by using the following settings in `mk/build.mk`:

```
include mk/flavours/devel2.mk
GhcLibHcOpts       = -O0 -dcore-lint
GhcLibWays = v
DYNAMIC_GHC_PROGRAMS = NO
```

ghc-stage2: /home/travis/build/snowleopard/hadrian/ghc/_build/stage1/libraries/base/HSbase-4.9.0.0.o: unknown symbol `stat'

But GHC's Travis runs are succeeding, and it uses almost the same settings:

```
- echo 'DYNAMIC_GHC_PROGRAMS = NO' >> mk/validate.mk
- echo 'GhcLibWays = v' >> mk/validate.mk
```

I'm not going to investigate further now, but there's a start.

**Comment by thomie** [comment]
I opened https://ghc.haskell.org/trac/ghc/ticket/12169.

Workaround: build the libraries with `-O` instead of `-O0` (src/Settings/Flavours/Quick.hs).

**Comment by snowleopard** [comment]
@KaiHa @thomie Many thanks for investigating this! 

Do you know if the issue can be fixed properly soon? If not, shall we temporarily use `-O` instead of `-O0` on Linux in the `quick` flavour? That would bring the CI back. If we opt for the latter option, I'd appreciate some pointers on specific condition we should use for the workaround: should it be just `anyTargetOs ["linux"]` or anything more complicated, e.g. `arch`-specific?

**Comment by thomie** [comment]
It might well take a while before it gets fixed. A build configuration of DYNAMIC_GHC_PROGRAMS=NO and libraries without optimization is not a configuration that many people use. I don't even know if it has ever worked, though I'm a bit surprised it doesn't.

Here's what you could do: make Hadrian's build flavour quick the same as the old build system's:
```
GhcStage1HcOpts    = -O    # So that (re)building stage2 is fast (important for ghc developers).
GhcStage2HcOpts    = -O0     
GhcLibHcOpts       = -O
```

So use `-O` for the libraries, but not for the stage2 compiler.

Then, add a `Quickest` build flavour, just like the old build system has. This one is the same as above, except use `-O0` for the libraries. You could use Quickest yourself for Hadrian development.

**Comment by snowleopard** [comment]
Thanks @thomie! This sounds like a good way forward, I'll do that.

**Comment by KaiHa** [comment]
> Workaround: build the libraries with -O instead of -O0 (src/Settings/Flavours/Quick.hs).

@thomie @snowleopard For the record, this does not help with the `unhandled ELF relocation(RelA) type 42` error. But since this error seems to be related to the unfortunate combination of _binutils_ and _libc6_ versions on my build system, I doubt that hadrian needs a fix for this.

**Comment by thomie** [comment]
> this error seems to be related to the unfortunate combination of binutils and libc6 versions on my build system

If you think GHC can do better here, like for example detect this mismatch at configure time, please mention it in https://ghc.haskell.org/trac/ghc/ticket/12147.

**Comment by erikd** [comment]
@michalt @KaiHa Can you please provide details of your Linux distribution as well as your `libc` and `binutils` versions?

**Comment by KaiHa** [comment]
> Can you please provide details of your Linux distribution as well as your libc and binutils versions?

Debian GNU/Linux testing
binutils  2.26-10  amd64
libc6:amd64  2.22-11  amd64

**Comment by michalt** [comment]
@erikd Fedora 24:
```
glibc.x86_64                          2.23.1-7.fc24
binutils.x86_64                       2.26-18.fc24
```

**Comment by snowleopard** [comment]
I've fixed the `unknown symbol stat` issue, so we finally have green light from all CI bots. @thomie I guess the same solution (see the last commit) could be used in GHC to fix ticket 12169?

@KaiHa What is the status of your `error 42`? Can we close this issue?

**Comment by KaiHa** [comment]
On my setup I still get the `error 42`. I don't know how to proceed. I am willing to accept that this is a problem of my setup that will vanish as soon as I get a glibc > 2.23.

**Comment by snowleopard** [comment]
@KaiHa Right, so it looks like we really can't do anything about this on the Hadrian side. I've changed the issue labels to clarify this.

I'll keep the issue open for now, as people might spot it and offer a fix.

**Comment by snowleopard** [comment]
There's been no activity here for half a year, so I take this is no longer an issue and can be closed. Feel free to reopen if the error reoccurs.

**Comment by siddhanathan** [comment]
I've been having this issue. Tried both quick and quickest flavors. Is there a workaround? Using `GLIBC 2.23-0ubuntu5` on Ubuntu 16.04

**Comment by snowleopard** [comment]
@siddhanathan Can you do a successful build using the Make build system? I can't reproduce this issue myself, so it's hard for me to investigate.
