### ISSUE TITLE
Missing dependency on package database

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#421]
I am seeing the following while trying to build GHC 8f468fe05cf81ca516b3a8cf66792f842dbfcf40 with hadrian 68446abeab92087492baba6c746ab94c3bb7c2bb,
```
<command line>: unknown package: rts
shakeArgsWith   0.000s    0%
Function shake  0.220s    0%
Database read   0.006s    0%
With database   0.027s    0%
Running rules  47.492s   99%  =========================
Total          47.745s  100%
Error when running Shake build system:
* _build/stage1/rts/libHSrtsthr_l_-ghc8.3.20170926.so
* _build/stage1/rts/cmm/Updates.dyn_o
user error (Development.Shake.cmd, system command failed
Command: inplace/bin/ghc-stage1 -Wall -hisuf dyn_hi -osuf dyn_o -hcsuf dyn_hc -fPIC -dynamic -i -i_build/stage1/rts -i_build/stage1/rts/build/autogen -Iincludes -I_build/generated -I_build/stage1/rts -I_build/generated -optc-I_build/generated -optc-fno-stack-protector -odir _build/stage1/rts -hidir _build/stage1/rts -stubdir _build/stage1/rts -c rts/Updates.cmm -o _build/stage1/rts/cmm/Updates.dyn_o -O2 -H32m -Werror -optc-Werror=unused-but-set-variable -optc-Wno-error=inline -Irts -Wno-deprecated-flags
Exit code: 1
Stderr:
<command line>: unknown package: rts

)
```

**Comment by snowleopard** [comment]
Looks like this is related to the `dynamic` way.

@izgzhen Any ideas?

**Comment by snowleopard** [comment]
@bgamari Thanks for reporting. Was it the default command `build -j`?

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari Thanks for reporting. Was it the default command `build -j`?
>
Yep.

**Comment by izgzhen** [comment]
I can't reproduce that with newer GHC on my Linux machine. I will try build the exact GHC version later.

**Comment by bgamari** [comment]
Two differences that I noticed between the Make build system and the command line produced by Shake,

 * Shake doesn't pass `-DCOMPILING_RTS`
 * Shake doesn't pass `-this-unit-id rts `

Unfortunately neither of these seem to make a difference.

**Comment by izgzhen** [comment]
I can't reproduce with GHC 8f468f either ...

**Comment by bgamari** [comment]
For the record, the inplace package database also appears to be empty; I haven't confirmed but I suspect this is the issue. I berlieve you need to register the `rts` package before attempting to build it.

**Comment by bgamari** [comment]
I had thought that perhaps this was just a race between the package registration and build. However, manually running `hadrian inplace/lib/package.conf.d/.stamp` and then rerunning `hadrian` doesn't appear to work either.

**Comment by bgamari** [comment]
Oh dear; it seems I was just pulling from the wrong remote. Many apologies for the noise.

**Comment by bgamari** [comment]
Never mind, I was pulling from the right remote; in the above comment I was just looking at the wrong GHC tree. I'll leave a fresh build running overnight as it's possible this issue was just due to stale files in my GHC tree.

Clearly it's time to go to sleep.

**Comment by snowleopard** [comment]
@bgamari This is just a missing dependency, unrelated to the `dynamic` way. Here is how to reproduce:
* Do full build.
* Delete `inplace\lib\package.conf.d`
* Delete `_build\stage1\rts\cmm\Updates.o`
* Run Hadrian with target `_build\stage1\rts\cmm\Updates.o`.

I'll try to fix this tonight.

**Comment by bgamari** [comment]
Well, it seems that the build finished. I suspect the problem was simply stale files from the old build system left in the tree. Sorry again for the noise!

**Comment by snowleopard** [comment]
@bgamari Let me reopen this under a revised title, since I think there is a bug in Hadrian related to a missing dependency on the package database.

**Comment by snowleopard** [comment]
The above commit should fix the missing dependency, so I'm now closing this.

**Comment by bgamari** [comment]
Unfortunately I still see a variant of this while cross-compiling. See #431.
